apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{Values.image.repository}}
    tag: {{Values.image.tag}}
  name: nginx-alpine
  namespace: {{Values.namespace.name}}
spec:
  replicas: {{Values.replicas}}
  selector:
    matchLabels:
      app: nginx
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{Values.image.repository}}
        tag: {{Values.image.tag}}
    spec:
      containers:
      - image: {{Values.image.repository}}:{{Values.image.tag}}
        imagePullPolicy: {{Values.image.pull-policy}}
        name: nginx-alpine
        resources:
          limits:
            cpu: {{Values.resources.cpu}}
            memory: {{Values.resources.memory}}